spring:
  datasource:
    url: jdbc:mysql://springboot-database.cmpfriqqwrwg.ap-northeast-2.rds.amazonaws.com/myselectshop
    username: admin
    password: jsoishop
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    oauth2:
      client:
        clientid:
          clientSecret:
server:
  port:8080